todo/todo_list/home/urls.py
from . import views
from django.urls import path


app_name = "website"


urlpatterns = [
    path("", views.index, name="home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register, name="register")
]

todo/todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls"))
]

todo/todo_list/home/models.py
from django.db import models

# Create your models here.

class recordUsers(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    nickname = models.CharField(max_length=50)
    password = models.CharField(max_length=100)


    def __str__(self):
        return self.nickname

todo/todo_list/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import recordUsers

todo/todo_list/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    return render(request, "index.html", {})



def register(request):
    return render(request, "register.html", {})



def login_user(request):
    if request.method == "POST":
        nickname = request.POST['nickname']
        password = request.POST['password']

        user = authenticate(request, username=nickname, password=password)

        if user is not None:
            login(request, user)
            return redirect("website:home")

        else:
            return redirect("website:login")

    else:
        return render(request, "login.html", {})

todo/todo_list/home/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}

<h1>This is the main page</h1>

{% endblock %}

todo/todo_list/home/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>Document</title>
</head>
<body>
    
    {% block body %}

    {% endblock %}

</body>
</html>

todo/todo_list/home/templates/login.html
{% extends 'layout.html' %}

{% block body %}

    <div class="container">
        <div class="login-form-wrapper">
            <div class="login-form-inner">
                <div class="login-form-data">
                    <h1>Welcome</h1>
                    <p>New here? <a href="{% url 'website:register' %}">Register</a></p>
                </div>
    
                <form action="{% url 'website:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-wrapper">
                        <input type="text" name="nickname" placeholder="Nickname" autocomplete="off">
                    </div>
    
                    <div class="input-wrapper">
                        <input type="password" placeholder="Password" name="password" autocomplete="off">
                    </div>
    
                    <input type="submit" value="Login" class="login-button">
    
                </form>
            </div>
        </div>
    </div>

{% endblock %}

todo/todo_list/home/templates/register.html
{% extends 'layout.html' %}

{% block body %}

    <h2>we are on the register page</h2>

{% endblock %}